# 元祖一但定义不允许修改
tuple_sample =("zhangsan",18,1.78)
print(tuple_sample)
print(tuple_sample.count(18))
print(type(tuple_sample))
print(tuple_sample.index(18))
print(tuple_sample[1])
print(len(tuple_sample))
tuple_empty =()
print(type(tuple_empty))